apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test-ns
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-ns
  labels:
    app: nginx-app
spec:
  ports:
  - name: nginx-servers-port
    port: 80
  type: NodePort
  selector:
    app: nginx-app
