apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
  namespace: test-ns
reclaimPolicy: Retain
spec:
  capacity:
   storage: 50Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/opt/data"
  storageClassName: slow
